### ISSUE TITLE
Pressing ESC doesn't pause the background video

### ISSUE THREAD

**Issue by Boing7678** [Pawlogates/arabfunny_controller#1]
idk if this is intentional but if you press escape to pause the video generation and recover your hearing, the background video continues playing.

Very nice program allah approved ✅✅✅2015 free software download تحميل النسخة العربية مجانا link no adfly skip instant تثبيت النسخة الحلال من برنامج crazy mega easy install‼️‼️‼️

**Comment by MauroPle** [comment]
This is the dumbest thing I've ever seen. You have all my respect.

**Comment by Pawlogates** [comment]
Thanks for checking it out :v idk why i suddenly had to make this but its
too late now. The background video not being paused is not intentional, but
i was also aware of it from the start but just couldnt be bothered to fix
that ;3;

pt., 23 sie 2024, 21:49 użytkownik MauroPle ***@***.***>
napisał:
